"""Core package for shared TRANSITIONS utilities."""

from .config import (
    COMPETITIONS_CSV_PATH,
    EPV_DAS_MIN_DURATION_SECONDS,
    EPV_DAS_THRESHOLD,
    EPV_MOMENTUM_WINDOW_SECONDS,
    FORMATION_GK_MIN_FRAMES,
    FORMATION_MIN_FRAMES_PER_WINDOW,
    FORMATION_MIN_OUTFIELD_PLAYERS,
    FORMATION_STRIDE_SECONDS,
    FORMATION_WINDOW_SECONDS,
    POSSESSION_MIN_SEQUENCE_SECONDS,
    POSSESSION_SMOOTH_WINDOW_SECONDS,
    POSSESSION_THRESHOLD_M,
    PROCESSED_DIR,
    RAW_EVENTS_DIR,
    RAW_METADATA_DIR,
    RAW_ROSTERS_DIR,
    RAW_TRACKING_DIR,
    RESOURCE_DIR,
    PLAYERS_CSV_PATH,
)
from .constants import (
    DEFAULT_COMPETITIONS_CSV,
    DEFAULT_DATA_DIR,
    DEFAULT_PLAYERS_CSV,
    DEFAULT_PROCESSED_DIR,
    DEFAULT_RAW_EVENTS_DIR,
    DEFAULT_RAW_METADATA_DIR,
    DEFAULT_RAW_ROSTERS_DIR,
    DEFAULT_RAW_TRACKING_DIR,
    DEFAULT_RESOURCE_DIR,
)
from .exceptions import ConfigurationError, DataLoadError, TransitionsError
from .version import __version__
