"""Central configuration defaults for TRANSITIONS."""

from ..io.paths import (
    COMPETITIONS_CSV_PATH,
    PLAYERS_CSV_PATH,
    PROCESSED_DIR as _PROCESSED_DIR,
    RAW_EVENTS_DIR as _RAW_EVENTS_DIR,
    RAW_METADATA_DIR as _RAW_METADATA_DIR,
    RAW_ROSTERS_DIR as _RAW_ROSTERS_DIR,
    RAW_TRACKING_DIR as _RAW_TRACKING_DIR,
    RESOURCE_DIR as _RESOURCE_DIR,
)

RAW_METADATA_DIR = str(_RAW_METADATA_DIR)
RAW_TRACKING_DIR = str(_RAW_TRACKING_DIR)
RAW_ROSTERS_DIR = str(_RAW_ROSTERS_DIR)
RAW_EVENTS_DIR = str(_RAW_EVENTS_DIR)
PROCESSED_DIR = str(_PROCESSED_DIR)
RESOURCE_DIR = str(_RESOURCE_DIR)
PLAYERS_CSV_PATH = str(PLAYERS_CSV_PATH)
COMPETITIONS_CSV_PATH = str(COMPETITIONS_CSV_PATH)

FORMATION_WINDOW_SECONDS = 180
FORMATION_STRIDE_SECONDS = 60
FORMATION_MIN_FRAMES_PER_WINDOW = 30
FORMATION_MIN_OUTFIELD_PLAYERS = 9
FORMATION_GK_MIN_FRAMES = 3000

# Windows whose best-vs-second-best template cost margin (metres per player)
# falls below this are flagged as ambiguous: the label is not trustworthy.
AMBIGUOUS_MARGIN_M = 0.75

POSSESSION_THRESHOLD_M = 2.5
POSSESSION_SMOOTH_WINDOW_SECONDS = 1.0
POSSESSION_MIN_SEQUENCE_SECONDS = 2.0

EPV_DAS_THRESHOLD = 0.15
EPV_DAS_MIN_DURATION_SECONDS = 2.0
EPV_MOMENTUM_WINDOW_SECONDS = 45.0
